<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PredikatAssessmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $assessments = [
            // Data yang Anda berikan (300 baris)
            [1, 'Kurang', 'Kurang', 'Kurang', 'Kurang', 'Kurang'],
            [2, 'Kurang', 'Kurang', 'Kurang', 'Cukup', 'Kurang'],
            [3, 'Kurang', 'Kurang', 'Cukup', 'Cukup', 'Kurang'],
            [4, 'Kurang', 'Cukup', 'Cukup', 'Cukup', 'Kurang'],
            [5, 'Cukup', 'Cukup', 'Cukup', 'Kurang', 'Kurang'],
            [6, 'Kurang', 'Cukup', 'Kurang', 'Cukup', 'Kurang'],
            [7, 'Kurang', 'Kurang', 'Cukup', 'Kurang', 'Kurang'],
            [8, 'Kurang', 'Cukup', 'Kurang', 'Kurang', 'Kurang'],
            [9, 'Cukup', 'Cukup', 'Cukup', 'Cukup', 'Cukup'],
            [10, 'Cukup', 'Cukup', 'Cukup', 'Kurang', 'Kurang'],
            [11, 'Cukup', 'Cukup', 'Kurang', 'Kurang', 'Kurang'],
            [12, 'Cukup', 'Kurang', 'Kurang', 'Kurang', 'Kurang'],
            [13, 'Cukup', 'Kurang', 'Kurang', 'Cukup', 'Kurang'],
            [14, 'Cukup', 'Kurang', 'Cukup', 'Kurang', 'Kurang'],
            [15, 'Cukup', 'Cukup', 'Kurang', 'Cukup', 'Kurang'],
            [16, 'Cukup', 'Kurang', 'Cukup', 'Cukup', 'Kurang'],
            [17, 'Kurang', 'Kurang', 'Kurang', 'Baik', 'Kurang'],
            [18, 'Kurang', 'Kurang', 'Baik', 'Baik', 'Kurang'],
            [19, 'Kurang', 'Baik', 'Baik', 'Baik', 'Cukup'],
            [20, 'Kurang', 'Baik', 'Baik', 'Kurang', 'Kurang'],
            [21, 'Kurang', 'Baik', 'Kurang', 'Baik', 'Kurang'],
            [22, 'Kurang', 'Kurang', 'Baik', 'Kurang', 'Kurang'],
            [23, 'Kurang', 'Baik', 'Kurang', 'Kurang', 'Kurang'],
            [24, 'Baik', 'Baik', 'Baik', 'Baik', 'Baik'],
            [25, 'Baik', 'Baik', 'Baik', 'Kurang', 'Cukup'],
            [26, 'Baik', 'Baik', 'Kurang', 'Kurang', 'Kurang'],
            [27, 'Baik', 'Kurang', 'Kurang', 'Kurang', 'Kurang'],
            [28, 'Baik', 'Kurang', 'Kurang', 'Baik', 'Kurang'],
            [29, 'Baik', 'Kurang', 'Baik', 'Kurang', 'Kurang'],
            [30, 'Baik', 'Baik', 'Kurang', 'Baik', 'Cukup'],
            [31, 'Baik', 'Kurang', 'Baik', 'Baik', 'Cukup'],
            [32, 'Kurang', 'Kurang', 'Kurang', 'Sangat Baik', 'Kurang'],
            [33, 'Kurang', 'Kurang', 'Sangat Baik', 'Sangat Baik', 'Kurang'],
            [34, 'Kurang', 'Sangat Baik', 'Sangat Baik', 'Sangat Baik', 'Cukup'],
            [35, 'Kurang', 'Sangat Baik', 'Sangat Baik', 'Kurang', 'Kurang'],
            [36, 'Kurang', 'Sangat Baik', 'Kurang', 'Sangat Baik', 'Kurang'],
            [37, 'Kurang', 'Kurang', 'Sangat Baik', 'Kurang', 'Kurang'],
            [38, 'Kurang', 'Sangat Baik', 'Kurang', 'Kurang', 'Kurang'],
            [39, 'Sangat Baik', 'Sangat Baik', 'Sangat Baik', 'Sangat Baik', 'Sangat Baik'],
            [40, 'Sangat Baik', 'Sangat Baik', 'Sangat Baik', 'Kurang', 'Cukup'],
            [41, 'Sangat Baik', 'Sangat Baik', 'Kurang', 'Kurang', 'Cukup'],
            [42, 'Sangat Baik', 'Kurang', 'Kurang', 'Kurang', 'Kurang'],
            [43, 'Sangat Baik', 'Kurang', 'Kurang', 'Sangat Baik', 'Kurang'],
            [44, 'Sangat Baik', 'Kurang', 'Sangat Baik', 'Kurang', 'Kurang'],
            [45, 'Sangat Baik', 'Sangat Baik', 'Kurang', 'Sangat Baik', 'Cukup'],
            [46, 'Sangat Baik', 'Kurang', 'Sangat Baik', 'Sangat Baik', 'Cukup'],
            [47, 'Kurang', 'Kurang', 'Kurang', 'Istimewa', 'Kurang'],
            [48, 'Kurang', 'Kurang', 'Istimewa', 'Istimewa', 'Kurang'],
            [49, 'Kurang', 'Istimewa', 'Istimewa', 'Istimewa', 'Cukup'],
            [50, 'Kurang', 'Istimewa', 'Istimewa', 'Kurang', 'Kurang'],
            [51, 'Kurang', 'Istimewa', 'Kurang', 'Istimewa', 'Kurang'],
            [52, 'Kurang', 'Kurang', 'Istimewa', 'Kurang', 'Kurang'],
            [53, 'Kurang', 'Istimewa', 'Kurang', 'Kurang', 'Kurang'],
            [54, 'Istimewa', 'Istimewa', 'Istimewa', 'Istimewa', 'Istimewa'],
            [55, 'Istimewa', 'Istimewa', 'Istimewa', 'Kurang', 'Cukup'],
            [56, 'Istimewa', 'Istimewa', 'Kurang', 'Kurang', 'Cukup'],
            [57, 'Istimewa', 'Kurang', 'Kurang', 'Kurang', 'Kurang'],
            [58, 'Istimewa', 'Kurang', 'Kurang', 'Istimewa', 'Kurang'],
            [59, 'Istimewa', 'Kurang', 'Istimewa', 'Kurang', 'Cukup'],
            [60, 'Istimewa', 'Istimewa', 'Kurang', 'Istimewa', 'Cukup'],
            [61, 'Istimewa', 'Kurang', 'Istimewa', 'Istimewa', 'Cukup'],
            [62, 'Cukup', 'Cukup', 'Cukup', 'Baik', 'Cukup'],
            [63, 'Cukup', 'Cukup', 'Baik', 'Baik', 'Cukup'],
            [64, 'Cukup', 'Baik', 'Baik', 'Baik', 'Cukup'],
            [65, 'Cukup', 'Baik', 'Baik', 'Cukup', 'Cukup'],
            [66, 'Cukup', 'Baik', 'Cukup', 'Baik', 'Cukup'],
            [67, 'Cukup', 'Cukup', 'Baik', 'Cukup', 'Cukup'],
            [68, 'Cukup', 'Baik', 'Cukup', 'Cukup', 'Cukup'],
            [69, 'Baik', 'Baik', 'Baik', 'Cukup', 'Baik'],
            [70, 'Baik', 'Baik', 'Cukup', 'Cukup', 'Cukup'],
            [71, 'Baik', 'Cukup', 'Cukup', 'Cukup', 'Cukup'],
            [72, 'Baik', 'Cukup', 'Cukup', 'Baik', 'Cukup'],
            [73, 'Baik', 'Cukup', 'Baik', 'Cukup', 'Cukup'],
            [74, 'Baik', 'Baik', 'Cukup', 'Baik', 'Cukup'],
            [75, 'Baik', 'Cukup', 'Baik', 'Baik', 'Cukup'],
            [76, 'Cukup', 'Cukup', 'Cukup', 'Sangat Baik', 'Cukup'],
            [77, 'Cukup', 'Cukup', 'Sangat Baik', 'Sangat Baik', 'Cukup'],
            [78, 'Cukup', 'Sangat Baik', 'Sangat Baik', 'Sangat Baik', 'Cukup'],
            [79, 'Cukup', 'Sangat Baik', 'Sangat Baik', 'Cukup', 'Cukup'],
            [80, 'Cukup', 'Sangat Baik', 'Cukup', 'Sangat Baik', 'Cukup'],
            [81, 'Cukup', 'Cukup', 'Sangat Baik', 'Cukup', 'Cukup'],
            [82, 'Cukup', 'Sangat Baik', 'Cukup', 'Cukup', 'Cukup'],
            [83, 'Sangat Baik', 'Sangat Baik', 'Sangat Baik', 'Cukup', 'Sangat Baik'],
            [84, 'Sangat Baik', 'Sangat Baik', 'Cukup', 'Cukup', 'Cukup'],
            [85, 'Sangat Baik', 'Cukup', 'Cukup', 'Cukup', 'Cukup'],
            [86, 'Sangat Baik', 'Cukup', 'Cukup', 'Sangat Baik', 'Cukup'],
            [87, 'Sangat Baik', 'Cukup', 'Sangat Baik', 'Cukup', 'Cukup'],
            [88, 'Sangat Baik', 'Sangat Baik', 'Cukup', 'Sangat Baik', 'Cukup'],
            [89, 'Sangat Baik', 'Cukup', 'Sangat Baik', 'Sangat Baik', 'Cukup'],
            [90, 'Cukup', 'Cukup', 'Cukup', 'Istimewa', 'Cukup'],
            [91, 'Cukup', 'Cukup', 'Istimewa', 'Istimewa', 'Cukup'],
            [92, 'Cukup', 'Istimewa', 'Istimewa', 'Istimewa', 'Cukup'],
            [93, 'Cukup', 'Istimewa', 'Istimewa', 'Cukup', 'Cukup'],
            [94, 'Cukup', 'Istimewa', 'Cukup', 'Istimewa', 'Cukup'],
            [95, 'Cukup', 'Cukup', 'Istimewa', 'Cukup', 'Cukup'],
            [96, 'Cukup', 'Istimewa', 'Cukup', 'Cukup', 'Cukup'],
            [97, 'Istimewa', 'Istimewa', 'Istimewa', 'Cukup', 'Sangat Baik'],
            [98, 'Istimewa', 'Istimewa', 'Cukup', 'Cukup', 'Cukup'],
            [99, 'Istimewa', 'Cukup', 'Cukup', 'Cukup', 'Cukup'],
            [100, 'Istimewa', 'Cukup', 'Cukup', 'Istimewa', 'Cukup'],
            [101, 'Istimewa', 'Cukup', 'Istimewa', 'Cukup', 'Cukup'],
            [102, 'Istimewa', 'Istimewa', 'Cukup', 'Istimewa', 'Cukup'],
            [103, 'Istimewa', 'Cukup', 'Istimewa', 'Istimewa', 'Cukup'],
            [104, 'Baik', 'Baik', 'Baik', 'Sangat Baik', 'Baik'],
            [105, 'Baik', 'Baik', 'Sangat Baik', 'Sangat Baik', 'Sangat Baik'],
            [106, 'Baik', 'Sangat Baik', 'Sangat Baik', 'Sangat Baik', 'Sangat Baik'],
            [107, 'Baik', 'Sangat Baik', 'Sangat Baik', 'Baik', 'Sangat Baik'],
            [108, 'Baik', 'Sangat Baik', 'Baik', 'Sangat Baik', 'Sangat Baik'],
            [109, 'Baik', 'Baik', 'Sangat Baik', 'Baik', 'Baik'],
            [110, 'Baik', 'Sangat Baik', 'Baik', 'Baik', 'Baik'],
            [111, 'Sangat Baik', 'Sangat Baik', 'Sangat Baik', 'Baik', 'Sangat Baik'],
            [112, 'Sangat Baik', 'Sangat Baik', 'Baik', 'Baik', 'Sangat Baik'],
            [113, 'Sangat Baik', 'Baik', 'Baik', 'Baik', 'Baik'],
            [114, 'Sangat Baik', 'Baik', 'Baik', 'Sangat Baik', 'Sangat Baik'],
            [115, 'Sangat Baik', 'Baik', 'Sangat Baik', 'Baik', 'Sangat Baik'],
            [116, 'Sangat Baik', 'Sangat Baik', 'Baik', 'Sangat Baik', 'Sangat Baik'],
            [117, 'Sangat Baik', 'Baik', 'Sangat Baik', 'Sangat Baik', 'Sangat Baik'],
            [118, 'Baik', 'Baik', 'Baik', 'Istimewa', 'Sangat Baik'],
            [119, 'Baik', 'Baik', 'Istimewa', 'Istimewa', 'Sangat Baik'],
            [120, 'Baik', 'Istimewa', 'Istimewa', 'Istimewa', 'Sangat Baik'],
            [121, 'Baik', 'Istimewa', 'Istimewa', 'Baik', 'Sangat Baik'],
            [122, 'Baik', 'Istimewa', 'Baik', 'Istimewa', 'Sangat Baik'],
            [123, 'Baik', 'Baik', 'Istimewa', 'Baik', 'Sangat Baik'],
            [124, 'Baik', 'Istimewa', 'Baik', 'Baik', 'Baik'],
            [125, 'Istimewa', 'Istimewa', 'Istimewa', 'Baik', 'Sangat Baik'],
            [126, 'Istimewa', 'Istimewa', 'Baik', 'Baik', 'Sangat Baik'],
            [127, 'Istimewa', 'Baik', 'Baik', 'Baik', 'Baik'],
            [128, 'Istimewa', 'Baik', 'Baik', 'Istimewa', 'Sangat Baik'],
            [129, 'Istimewa', 'Baik', 'Istimewa', 'Baik', 'Sangat Baik'],
            [130, 'Istimewa', 'Istimewa', 'Baik', 'Istimewa', 'Sangat Baik'],
            [131, 'Istimewa', 'Baik', 'Istimewa', 'Istimewa', 'Sangat Baik'],
            [132, 'Sangat Baik', 'Sangat Baik', 'Sangat Baik', 'Istimewa', 'Sangat Baik'],
            [133, 'Sangat Baik', 'Sangat Baik', 'Istimewa', 'Istimewa', 'Sangat Baik'],
            [134, 'Sangat Baik', 'Istimewa', 'Istimewa', 'Istimewa', 'Sangat Baik'],
            [135, 'Sangat Baik', 'Istimewa', 'Istimewa', 'Sangat Baik', 'Sangat Baik'],
            [136, 'Sangat Baik', 'Istimewa', 'Sangat Baik', 'Istimewa', 'Sangat Baik'],
            [137, 'Sangat Baik', 'Sangat Baik', 'Istimewa', 'Sangat Baik', 'Sangat Baik'],
            [138, 'Sangat Baik', 'Istimewa', 'Sangat Baik', 'Sangat Baik', 'Sangat Baik'],
            [139, 'Istimewa', 'Istimewa', 'Istimewa', 'Sangat Baik', 'Sangat Baik'],
            [140, 'Istimewa', 'Istimewa', 'Sangat Baik', 'Sangat Baik', 'Sangat Baik'],
            [141, 'Istimewa', 'Sangat Baik', 'Sangat Baik', 'Sangat Baik', 'Sangat Baik'],
            [142, 'Istimewa', 'Sangat Baik', 'Sangat Baik', 'Istimewa', 'Sangat Baik'],
            [143, 'Istimewa', 'Sangat Baik', 'Istimewa', 'Sangat Baik', 'Sangat Baik'],
            [144, 'Istimewa', 'Istimewa', 'Sangat Baik', 'Istimewa', 'Sangat Baik'],
            [145, 'Istimewa', 'Sangat Baik', 'Istimewa', 'Istimewa', 'Sangat Baik'],
            [146, 'Kurang', 'Kurang', 'Cukup', 'Baik', 'Kurang'],
            [147, 'Kurang', 'Kurang', 'Baik', 'Cukup', 'Kurang'],
            [148, 'Kurang', 'Cukup', 'Cukup', 'Baik', 'Kurang'],
            [149, 'Kurang', 'Baik', 'Baik', 'Cukup', 'Kurang'],
            [150, 'Kurang', 'Cukup', 'Baik', 'Kurang', 'Kurang'],
            [151, 'Kurang', 'Baik', 'Cukup', 'Kurang', 'Kurang'],
            [152, 'Kurang', 'Cukup', 'Kurang', 'Baik', 'Kurang'],
            [153, 'Kurang', 'Baik', 'Kurang', 'Cukup', 'Kurang'],
            [154, 'Kurang', 'Cukup', 'Baik', 'Cukup', 'Kurang'],
            [155, 'Kurang', 'Baik', 'Cukup', 'Baik', 'Kurang'],
            [156, 'Kurang', 'Cukup', 'Baik', 'Baik', 'Kurang'],
            [157, 'Kurang', 'Baik', 'Cukup', 'Cukup', 'Kurang'],
            [158, 'Cukup', 'Cukup', 'Kurang', 'Baik', 'Kurang'],
            [159, 'Cukup', 'Cukup', 'Baik', 'Kurang', 'Kurang'],
            [160, 'Cukup', 'Baik', 'Baik', 'Kurang', 'Kurang'],
            [161, 'Cukup', 'Kurang', 'Kurang', 'Baik', 'Kurang'],
            [162, 'Cukup', 'Baik', 'Kurang', 'Cukup', 'Kurang'],
            [163, 'Cukup', 'Kurang', 'Baik', 'Cukup', 'Kurang'],
            [164, 'Cukup', 'Baik', 'Cukup', 'Kurang', 'Kurang'],
            [165, 'Cukup', 'Kurang', 'Cukup', 'Baik', 'Kurang'],
            [166, 'Cukup', 'Baik', 'Kurang', 'Baik', 'Kurang'],
            [167, 'Cukup', 'Kurang', 'Baik', 'Kurang', 'Kurang'],
            [168, 'Cukup', 'Baik', 'Kurang', 'Kurang', 'Kurang'],
            [169, 'Cukup', 'Kurang', 'Baik', 'Baik', 'Kurang'],
            [170, 'Baik', 'Baik', 'Kurang', 'Cukup', 'Cukup'],
            [171, 'Baik', 'Baik', 'Cukup', 'Kurang', 'Cukup'],
            [172, 'Baik', 'Cukup', 'Cukup', 'Kurang', 'Kurang'],
            [173, 'Baik', 'Kurang', 'Kurang', 'Cukup', 'Kurang'],
            [174, 'Baik', 'Cukup', 'Kurang', 'Baik', 'Cukup'],
            [175, 'Baik', 'Kurang', 'Cukup', 'Baik', 'Cukup'],
            [176, 'Baik', 'Cukup', 'Baik', 'Kurang', 'Cukup'],
            [177, 'Baik', 'Kurang', 'Baik', 'Cukup', 'Cukup'],
            [178, 'Baik', 'Cukup', 'Kurang', 'Cukup', 'Cukup'],
            [179, 'Baik', 'Kurang', 'Cukup', 'Kurang', 'Kurang'],
            [180, 'Baik', 'Cukup', 'Kurang', 'Kurang', 'Kurang'],
            [181, 'Baik', 'Kurang', 'Cukup', 'Cukup', 'Cukup'],
            [182, 'Kurang', 'Kurang', 'Baik', 'Sangat Baik', 'Kurang'],
            [183, 'Kurang', 'Kurang', 'Sangat Baik', 'Baik', 'Kurang'],
            [184, 'Kurang', 'Baik', 'Baik', 'Sangat Baik', 'Cukup'],
            [185, 'Kurang', 'Sangat Baik', 'Sangat Baik', 'Baik', 'Cukup'],
            [186, 'Kurang', 'Baik', 'Sangat Baik', 'Kurang', 'Cukup'],
            [187, 'Kurang', 'Sangat Baik', 'Baik', 'Kurang', 'Cukup'],
            [188, 'Kurang', 'Baik', 'Kurang', 'Sangat Baik', 'Cukup'],
            [189, 'Kurang', 'Sangat Baik', 'Kurang', 'Baik', 'Cukup'],
            [190, 'Kurang', 'Baik', 'Sangat Baik', 'Baik', 'Cukup'],
            [191, 'Kurang', 'Sangat Baik', 'Baik', 'Sangat Baik', 'Cukup'],
            [192, 'Kurang', 'Baik', 'Sangat Baik', 'Sangat Baik', 'Cukup'],
            [193, 'Kurang', 'Sangat Baik', 'Baik', 'Baik', 'Cukup'],
            [194, 'Baik', 'Baik', 'Kurang', 'Sangat Baik', 'Cukup'],
            [195, 'Baik', 'Baik', 'Sangat Baik', 'Kurang', 'Cukup'],
            [196, 'Baik', 'Sangat Baik', 'Sangat Baik', 'Kurang', 'Cukup'],
            [197, 'Baik', 'Kurang', 'Kurang', 'Sangat Baik', 'Cukup'],
            [198, 'Baik', 'Sangat Baik', 'Kurang', 'Baik', 'Cukup'],
            [199, 'Baik', 'Kurang', 'Sangat Baik', 'Baik', 'Cukup'],
            [200, 'Baik', 'Sangat Baik', 'Baik', 'Kurang', 'Cukup'],
            [201, 'Baik', 'Kurang', 'Baik', 'Sangat Baik', 'Cukup'],
            [202, 'Baik', 'Sangat Baik', 'Kurang', 'Sangat Baik', 'Cukup'],
            [203, 'Baik', 'Kurang', 'Sangat Baik', 'Kurang', 'Cukup'],
            [204, 'Baik', 'Sangat Baik', 'Kurang', 'Kurang', 'Cukup'],
            [205, 'Baik', 'Kurang', 'Sangat Baik', 'Sangat Baik', 'Cukup'],
            [206, 'Sangat Baik', 'Sangat Baik', 'Kurang', 'Baik', 'Cukup'],
            [207, 'Sangat Baik', 'Sangat Baik', 'Baik', 'Kurang', 'Cukup'],
            [208, 'Sangat Baik', 'Baik', 'Baik', 'Kurang', 'Cukup'],
            [209, 'Sangat Baik', 'Kurang', 'Kurang', 'Baik', 'Cukup'],
            [210, 'Sangat Baik', 'Baik', 'Kurang', 'Sangat Baik', 'Cukup'],
            [211, 'Sangat Baik', 'Kurang', 'Baik', 'Sangat Baik', 'Cukup'],
            [212, 'Sangat Baik', 'Baik', 'Sangat Baik', 'Kurang', 'Cukup'],
            [213, 'Sangat Baik', 'Kurang', 'Sangat Baik', 'Baik', 'Cukup'],
            [214, 'Sangat Baik', 'Baik', 'Kurang', 'Baik', 'Cukup'],
            [215, 'Sangat Baik', 'Kurang', 'Baik', 'Kurang', 'Cukup'],
            [216, 'Sangat Baik', 'Baik', 'Kurang', 'Kurang', 'Cukup'],
            [217, 'Sangat Baik', 'Kurang', 'Baik', 'Baik', 'Cukup'],
            [218, 'Baik', 'Baik', 'Cukup', 'Sangat Baik', 'Cukup'],
            [219, 'Baik', 'Baik', 'Sangat Baik', 'Cukup', 'Baik'],
            [220, 'Baik', 'Cukup', 'Cukup', 'Sangat Baik', 'Cukup'],
            [221, 'Baik', 'Sangat Baik', 'Sangat Baik', 'Cukup', 'Baik'],
            [222, 'Baik', 'Cukup', 'Sangat Baik', 'Baik', 'Cukup'],
            [223, 'Baik', 'Sangat Baik', 'Cukup', 'Baik', 'Cukup'],
            [224, 'Baik', 'Cukup', 'Baik', 'Sangat Baik', 'Cukup'],
            [225, 'Baik', 'Sangat Baik', 'Baik', 'Cukup', 'Baik'],
            [226, 'Baik', 'Cukup', 'Sangat Baik', 'Cukup', 'Cukup'],
            [227, 'Baik', 'Sangat Baik', 'Cukup', 'Sangat Baik', 'Cukup'],
            [228, 'Baik', 'Cukup', 'Sangat Baik', 'Sangat Baik', 'Cukup'],
            [229, 'Baik', 'Sangat Baik', 'Cukup', 'Cukup', 'Cukup'],
            [230, 'Cukup', 'Cukup', 'Baik', 'Sangat Baik', 'Cukup'],
            [231, 'Cukup', 'Cukup', 'Sangat Baik', 'Baik', 'Cukup'],
            [232, 'Cukup', 'Sangat Baik', 'Sangat Baik', 'Baik', 'Cukup'],
            [233, 'Cukup', 'Baik', 'Baik', 'Sangat Baik', 'Cukup'],
            [234, 'Cukup', 'Sangat Baik', 'Baik', 'Cukup', 'Cukup'],
            [235, 'Cukup', 'Baik', 'Sangat Baik', 'Cukup', 'Cukup'],
            [236, 'Cukup', 'Sangat Baik', 'Cukup', 'Baik', 'Cukup'],
            [237, 'Cukup', 'Baik', 'Cukup', 'Sangat Baik', 'Cukup'],
            [238, 'Cukup', 'Sangat Baik', 'Baik', 'Sangat Baik', 'Cukup'],
            [239, 'Cukup', 'Baik', 'Sangat Baik', 'Baik', 'Cukup'],
            [240, 'Cukup', 'Sangat Baik', 'Baik', 'Baik', 'Cukup'],
            [241, 'Cukup', 'Baik', 'Sangat Baik', 'Sangat Baik', 'Cukup'],
            [242, 'Sangat Baik', 'Sangat Baik', 'Cukup', 'Baik', 'Cukup'],
            [243, 'Sangat Baik', 'Sangat Baik', 'Baik', 'Cukup', 'Baik'],
            [244, 'Sangat Baik', 'Baik', 'Baik', 'Cukup', 'Baik'],
            [245, 'Sangat Baik', 'Cukup', 'Cukup', 'Baik', 'Cukup'],
            [246, 'Sangat Baik', 'Baik', 'Cukup', 'Sangat Baik', 'Cukup'],
            [247, 'Sangat Baik', 'Cukup', 'Baik', 'Sangat Baik', 'Cukup'],
            [248, 'Sangat Baik', 'Baik', 'Sangat Baik', 'Cukup', 'Baik'],
            [249, 'Sangat Baik', 'Cukup', 'Sangat Baik', 'Baik', 'Cukup'],
            [250, 'Sangat Baik', 'Baik', 'Cukup', 'Baik', 'Cukup'],
            [251, 'Sangat Baik', 'Cukup', 'Baik', 'Cukup', 'Cukup'],
            [252, 'Sangat Baik', 'Baik', 'Cukup', 'Cukup', 'Cukup'],
            [253, 'Sangat Baik', 'Cukup', 'Baik', 'Baik', 'Cukup'],
            [254, 'Baik', 'Baik', 'Istimewa', 'Sangat Baik', 'Baik'],
            [255, 'Baik', 'Baik', 'Sangat Baik', 'Istimewa', 'Baik'],
            [256, 'Baik', 'Istimewa', 'Istimewa', 'Sangat Baik', 'Sangat Baik'],
            [257, 'Baik', 'Sangat Baik', 'Sangat Baik', 'Istimewa', 'Sangat Baik'],
            [258, 'Baik', 'Istimewa', 'Sangat Baik', 'Baik', 'Baik'],
            [259, 'Baik', 'Istimewa', 'Istimewa', 'Baik', 'Baik'],
            [260, 'Baik', 'Istimewa', 'Baik', 'Sangat Baik', 'Baik'],
            [261, 'Baik', 'Sangat Baik', 'Baik', 'Istimewa', 'Baik'],
            [262, 'Baik', 'Istimewa', 'Sangat Baik', 'Istimewa', 'Sangat Baik'],
            [263, 'Baik', 'Sangat Baik', 'Istimewa', 'Sangat Baik', 'Sangat Baik'],
            [264, 'Baik', 'Istimewa', 'Sangat Baik', 'Sangat Baik', 'Sangat Baik'],
            [265, 'Baik', 'Sangat Baik', 'Istimewa', 'Istimewa', 'Sangat Baik'],
            [266, 'Istimewa', 'Istimewa', 'Baik', 'Sangat Baik', 'Sangat Baik'],
            [267, 'Istimewa', 'Istimewa', 'Sangat Baik', 'Baik', 'Sangat Baik'],
            [268, 'Istimewa', 'Sangat Baik', 'Sangat Baik', 'Baik', 'Sangat Baik'],
            [269, 'Istimewa', 'Baik', 'Baik', 'Sangat Baik', 'Baik'],
            [270, 'Istimewa', 'Sangat Baik', 'Baik', 'Istimewa', 'Sangat Baik'],
            [271, 'Istimewa', 'Baik', 'Sangat Baik', 'Istimewa', 'Sangat Baik'],
            [272, 'Istimewa', 'Sangat Baik', 'Istimewa', 'Baik', 'Sangat Baik'],
            [273, 'Istimewa', 'Baik', 'Istimewa', 'Sangat Baik', 'Sangat Baik'],
            [274, 'Istimewa', 'Sangat Baik', 'Baik', 'Sangat Baik', 'Sangat Baik'],
            [275, 'Istimewa', 'Baik', 'Sangat Baik', 'Baik', 'Baik'],
            [276, 'Istimewa', 'Sangat Baik', 'Baik', 'Baik', 'Baik'],
            [277, 'Istimewa', 'Baik', 'Sangat Baik', 'Sangat Baik', 'Sangat Baik'],
            [278, 'Sangat Baik', 'Sangat Baik', 'Istimewa', 'Baik', 'Sangat Baik'],
            [279, 'Sangat Baik', 'Sangat Baik', 'Baik', 'Istimewa', 'Sangat Baik'],
            [280, 'Sangat Baik', 'Baik', 'Baik', 'Istimewa', 'Baik'],
            [281, 'Sangat Baik', 'Istimewa', 'Istimewa', 'Baik', 'Sangat Baik'],
            [282, 'Sangat Baik', 'Baik', 'Istimewa', 'Sangat Baik', 'Sangat Baik'],
            [283, 'Sangat Baik', 'Istimewa', 'Baik', 'Sangat Baik', 'Sangat Baik'],
            [284, 'Sangat Baik', 'Baik', 'Sangat Baik', 'Istimewa', 'Sangat Baik'],
            [285, 'Sangat Baik', 'Istimewa', 'Sangat Baik', 'Baik', 'Sangat Baik'],
            [286, 'Sangat Baik', 'Baik', 'Istimewa', 'Baik', 'Sangat Baik'],
            [287, 'Sangat Baik', 'Istimewa', 'Baik', 'Istimewa', 'Sangat Baik'],
            [288, 'Sangat Baik', 'Baik', 'Istimewa', 'Istimewa', 'Sangat Baik'],
            [289, 'Sangat Baik', 'Istimewa', 'Baik', 'Baik', 'Sangat Baik'],
            [290, 'Kurang', 'Kurang', 'Cukup', 'Sangat Baik', 'Kurang'],
            [291, 'Kurang', 'Kurang', 'Sangat Baik', 'Cukup', 'Kurang'],
            [292, 'Kurang', 'Cukup', 'Cukup', 'Sangat Baik', 'Cukup'],
            [293, 'Kurang', 'Sangat Baik', 'Sangat Baik', 'Cukup', 'Cukup'],
            [294, 'Kurang', 'Cukup', 'Sangat Baik', 'Kurang', 'Kurang'],
            [295, 'Kurang', 'Sangat Baik', 'Cukup', 'Kurang', 'Kurang'],
            [296, 'Kurang', 'Cukup', 'Kurang', 'Sangat Baik', 'Kurang'],
            [297, 'Kurang', 'Sangat Baik', 'Kurang', 'Cukup', 'Kurang'],
            [298, 'Kurang', 'Cukup', 'Sangat Baik', 'Cukup', 'Cukup'],
            [299, 'Kurang', 'Sangat Baik', 'Cukup', 'Sangat Baik', 'Cukup'],
            [300, 'Kurang', 'Cukup', 'Sangat Baik', 'Sangat Baik', 'Cukup'],
        ];

        foreach ($assessments as $assessment) {
            DB::table('predikat_assessments')->insert([
                'id' => $assessment[0],
                'a_poin' => $assessment[1],
                'b_poin' => $assessment[2],
                'c_poin' => $assessment[3],
                'd_poin' => $assessment[4],
                'predikat' => $assessment[5],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('Seeded 300 predikat assessments successfully.');
    }
}
