<?php

namespace Database\Seeders;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'id' => 1,
                'name' => 'Super User',
                'email' => 'admin@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2022-12-18 05:54:28'),
                'password' =>  Hash::make('password123'),
                'is_active' => true,
                'created_at' => Carbon::parse('2022-12-16 21:09:23'),
                'updated_at' => Carbon::parse('2022-12-18 06:14:57'),
                'remember_token' => null,
            ],
            [
                'id' => 8,
                'name' => 'Octo Zulkarnain, S.Kep., Ns., M.Imun.',
                'email' => 'o.zulkarnain@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2022-12-18 05:54:28'),
                'password' => '$2y$10$fiLwxKqNnFsM75G6YMe8OOMFpu05UiaDm/NHwC9aiqfLd8KggcuSy',
                'is_active' => true,
                'created_at' => Carbon::parse('2022-12-16 21:09:23'),
                'updated_at' => Carbon::parse('2022-12-18 06:14:57'),
                'remember_token' => null,
            ],
            [
                'id' => 9,
                'name' => 'Eko Budi Santoso, S.Kep.,Ns.,M.Kes',
                'email' => 'eko.santoso@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2022-12-16 22:00:04'),
                'password' => '$2y$10$xO2Pnwe5p/leBpqlskMxIuM9HRvJd1D2LHiw/jKz92DGjdwucIGC2',
                'is_active' => true,
                'created_at' => Carbon::parse('2022-12-16 21:52:39'),
                'updated_at' => Carbon::parse('2022-12-16 22:00:04'),
                'remember_token' => 'tz3AKSks8Er8kL3N3rO3t45hfXQBAzBjFrFpkYtbbev5RPe63kqWQWZ6Sw3f',
            ],
            [
                'id' => 11,
                'name' => 'Setiya Hartiningtiyaswati, M. Keb',
                'email' => 'setiya.hartiningtiyaswati@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2022-12-17 02:14:55'),
                'password' => '$2y$10$EmGyX1dk3HuwTd6ihxU9hO.gOrV97uqTp0oWrLrsLj3I.3vTf/Wlm',
                'is_active' => true,
                'created_at' => Carbon::parse('2022-12-17 02:11:44'),
                'updated_at' => Carbon::parse('2022-12-17 02:14:55'),
                'remember_token' => 'NQmpMObH2kLYQXjfuEmeBBsufEVEnZ2aTJKypJjYG3jsFAg3krB7OobTkvyB',
            ],
            [
                'id' => 13,
                'name' => 'Ariska Putri Hidayathillah, S.Kep.,Ns., M.Epid',
                'email' => 'ariska.hidayathillah@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2022-12-19 18:05:49'),
                'password' => '$2y$10$1LGXsOLPP4zHf7j2cmSkeurDwWYHHcxwn5lkSo7SFGxn7AcJ8F2Wm',
                'is_active' => true,
                'created_at' => Carbon::parse('2022-12-19 17:52:26'),
                'updated_at' => Carbon::parse('2025-11-05 07:36:46'),
                'remember_token' => '4uzbppkSxUeZFGoKLxGNQMc1iy8hKmOqzh0tiMPLXljeAP9KCS5vmbUtLE4t',
            ],
            [
                'id' => 14,
                'name' => 'Drs. Setiyawan Sukin Adiyanto., S.E., M.M.',
                'email' => 'setiyawan.adiyanto@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2022-12-22 23:49:12'),
                'password' => '$2y$10$7sLu0i4ejf88ZEtqJmU.2eWZ2c7LUFWLUhfIis5xy19ANptnUfRua',
                'is_active' => true,
                'created_at' => Carbon::parse('2022-12-22 23:37:20'),
                'updated_at' => Carbon::parse('2022-12-22 23:49:12'),
                'remember_token' => 'SFJVS7EYyDaiN4ygrXwTs18zNlxoFH23yKvrMERgeDm80c2CtwBBWaSddLuI',
            ],
            [
                'id' => 16,
                'name' => 'Ir. RR. Nurul Hidayati, M.Si.',
                'email' => 'nurul.hidayati@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2022-12-23 20:18:22'),
                'password' => '$2y$10$IUcrNpUw/JghsqDh9V5Q3uhVhJWYgU3u8cND9C57ZCcG86hLgSW5G',
                'is_active' => true,
                'created_at' => Carbon::parse('2022-12-23 20:17:01'),
                'updated_at' => Carbon::parse('2022-12-23 20:18:22'),
                'remember_token' => 'kk6IdzpNHRFBgU1gD16mJYd5qy951zv3zVcopCByTMI2O6KFXKfrDody1zgo',
            ],
            [
                'id' => 17,
                'name' => 'Retno Ayu Yuliastuti, S.Kep., Ns., M.Tr.Kep.',
                'email' => 'retno.ayu@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-02-02 18:21:39'),
                'password' => '$2y$10$bQzHVBv6GMikPWAFsNAoTOHLxNJjTgyFc2HUk/iiEfQ99srGbaGZC',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-02-01 19:36:25'),
                'updated_at' => Carbon::parse('2023-11-30 06:42:14'),
                'remember_token' => 'LBmpZwk30QYCY26mCAsP9MxdoNA7KcXfHOJNN9wtNDEdWTb3zFGvjgEk2eNx',
            ],
            [
                'id' => 18,
                'name' => 'Andi Hendra Susanto, S.Kom.',
                'email' => 'andi@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-02-15 23:40:58'),
                'password' => '$2y$10$of3bLANjBFl8HfWwMWLUY.syHzbh2ydwoa8fOlEogbMUhfTDoITAa',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-02-15 23:25:11'),
                'updated_at' => Carbon::parse('2025-06-17 18:43:39'),
                'remember_token' => 'CXwXw2kSF7Al2Q12zqDn9H1QicMgHHhsifLjfTlUHUyUe3cYRG7taru25jPy',
            ],
            [
                'id' => 66,
                'name' => 'Putri Pamungkas, S.Kep., Ns., M.KM.',
                'email' => 'putri.pamungkas@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-02-24 18:23:42'),
                'password' => '$2y$10$ecsl0uVbY9eYcku3bARvAOY7I5f9XBKJ.92v1jAmuEKOa1tF5RDOu',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-02-24 18:18:58'),
                'updated_at' => Carbon::parse('2023-02-24 18:23:42'),
                'remember_token' => 'w8J9TVSmWyvAZHqL4tmHmjFuobmmwymLlRpJlN1StzYUrL5VsnvrnPWKHKHK',
            ],
            [
                'id' => 67,
                'name' => 'Rasi Rahagia, S.Kep., Ns., M.Kep',
                'email' => 'rasi.rahagia@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-02-24 22:20:42'),
                'password' => '$2y$10$x4f8M1xo.Wocso/JPFcPoulYq6GrnR2ynfRKvqXHL7iKLe4jc9ZbK',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-02-24 22:15:35'),
                'updated_at' => Carbon::parse('2023-02-24 22:20:42'),
                'remember_token' => null,
            ],
            [
                'id' => 68,
                'name' => 'Heri Nur Cahyanto, S.Kep. Ns., M.T',
                'email' => 'hcahyanto@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-02-24 22:19:11'),
                'password' => '$2y$10$ezS5B2UWanrI7eAO.R0xBuYR0.dAvPB6lIqtdMsD3QiaWCEwqZu9K',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-02-24 22:17:41'),
                'updated_at' => Carbon::parse('2023-02-24 22:19:11'),
                'remember_token' => '74ZGGxRLMbCvGCGWXsogpcL7UjN6K1Blhky3GkyvwA2PfSFlFx6vuw0XEUGq',
            ],
            [
                'id' => 69,
                'name' => 'Denis Farida, S.Kep.,Ns.,M.Tr.Kep',
                'email' => 'denis.farida@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-02-27 17:05:01'),
                'password' => '$2y$10$tRn.oSKWkNt7EMioRt0mH.LHKnYcYEYVGRfpo668IA9I5JDDxpg8e',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-02-27 17:03:15'),
                'updated_at' => Carbon::parse('2023-02-27 17:05:01'),
                'remember_token' => 'hf7sjnWabIkmUWcB3JE4uwuFR1TUPmtiuCDWfuVV07bjXCmGwP2ofzVCYlWh',
            ],
            [
                'id' => 70,
                'name' => 'Alpian Jayadi, S.Kep.Ns., M.Imun',
                'email' => 'alpian.jayadi@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-02-27 17:33:33'),
                'password' => '$2a$12$787BUdXnX4dO3wWbL5t9GOefep/Y4eLNypYlxH2/a3OoqBeBEtJl6',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-02-27 17:33:08'),
                'updated_at' => Carbon::parse('2023-11-13 02:57:07'),
                'remember_token' => 'U1oKdkISUSf1RNGsoujIC1hFWtLeUjJhttnB4JzgDexa5lw5yS6BiDwjL5hN',
            ],
            [
                'id' => 71,
                'name' => 'Senatriya Wahyu Ramadhan, S.E., M.Ec.Dev.',
                'email' => 'senatriya.wahyu@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-03-02 17:06:59'),
                'password' => '$2y$10$aeuTmyOCOI4kEWDcMxQADujj..wux1jwzc5uHGbeIresPaZN9kntO',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-03-02 17:06:28'),
                'updated_at' => Carbon::parse('2023-03-02 17:06:59'),
                'remember_token' => 'ETqxXGLFr4aCNYIiTpwd7j8m4j7rscTyK8wNS71rsDJnQhgHla3dwLEDIApI',
            ],
            [
                'id' => 72,
                'name' => 'Zummatul Atika, SST., M.KM',
                'email' => 'zummatul.atika@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-03-02 21:04:25'),
                'password' => '$2y$10$6EGEl9We.7UnyNTnJLYf9.7zcmOzsd3LZcGINIHz55xdQzR/1Uahq',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-03-02 20:59:54'),
                'updated_at' => Carbon::parse('2023-03-02 21:04:25'),
                'remember_token' => 'gUplnJVn3Ep7Azut4e0zZrlWbfCtk3EpD48YRCBEczIaZuFZY6UQ076J9RiK',
            ],
            [
                'id' => 73,
                'name' => 'Zumrotul Ula, S.ST., M.Kes',
                'email' => 'zumrotul.ula@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-03-03 15:14:23'),
                'password' => '$2y$10$TVr2mZX6I.Nxx45WwPgwoec4wghlZtM1Pg8rLrNaD6pd8QuMZc6wi',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-03-03 15:12:36'),
                'updated_at' => Carbon::parse('2023-03-03 15:14:23'),
                'remember_token' => 'WRfUnHhq8j5jfzHrH8OAZD4HRyY8oAk1h3P8SZOd6UeNcQbcqkcVlm6DUB7t',
            ],
            [
                'id' => 74,
                'name' => 'Unziya Khodija, S.Gz., M.Gz.',
                'email' => 'unziya.khodija@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-03-03 20:58:36'),
                'password' => '$2y$10$V12oYTYzMw4iUrPlOjDSH.CU6P3S8oTEXudjFJ0BsmKhx6BfPuCv6',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-03-03 20:49:08'),
                'updated_at' => Carbon::parse('2023-03-03 20:58:36'),
                'remember_token' => null,
            ],
            [
                'id' => 75,
                'name' => 'Dr. M. Budi Widajanto, Drs., Ec., MP.',
                'email' => 'budi.widajanto@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-03-06 17:25:53'),
                'password' => '$2y$10$6GSeyvbjxhbT.OQzGQIIleTYinrhUT8stCVqDBInOmdtbLaPta18a',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-03-06 17:22:07'),
                'updated_at' => Carbon::parse('2023-07-18 04:08:27'),
                'remember_token' => 'CraJyu6VYr3kiTDfHqDLST9YanxRjDBvReMGgVadIcq0fjRH72RflgG4q5mf',
            ],
            [
                'id' => 80,
                'name' => 'Fidayatul Jamila, SST., M.Si',
                'email' => 'fidatul.jamila@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-03-15 18:25:01'),
                'password' => '$2y$10$jPwlm8qbORmankE.HtQEdecShwYFfbClFVdIc8E9SKKVC7l47t2HO',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-03-15 18:19:50'),
                'updated_at' => Carbon::parse('2023-03-15 18:25:01'),
                'remember_token' => 'mKqcLsjjntc065FQGMNjDZNHavtAPOPfeGZTQNJrLp2MyJKSv7QKckYxzt7g',
            ],
            [
                'id' => 81,
                'name' => 'Fajar Budi Nugroho',
                'email' => 'fajar@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-03-17 17:17:57'),
                'password' => '$2y$10$TjCwvtH4wpdJElQtqCHkeuiMBdV7SeOrl7CSxCo23i90waTdj/pTy',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-03-17 17:16:24'),
                'updated_at' => Carbon::parse('2023-03-17 17:17:57'),
                'remember_token' => null,
            ],
            [
                'id' => 82,
                'name' => 'Moch. Nur Kahfi, S.E.',
                'email' => 'kahfi@ikbis.ac.id',
                'email_verified_at' => null,
                'password' => '$2y$10$1B9qf9gSANiKYqihXxB.mOCTEwIELAzLJIQXm9dK09VxB5ncwQIAG',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-03-17 17:34:33'),
                'updated_at' => Carbon::parse('2025-10-28 15:41:15'),
                'remember_token' => null,
            ],
            [
                'id' => 83,
                'name' => 'Rini Novianti, S.K.M., S.E., MM',
                'email' => 'rini.novianti@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-03-17 23:55:32'),
                'password' => '$2y$10$gjh4.Yf9HPWs9WXRTIrVFOd7oP8javsC/NohwtnULZXHTZHgv.NFC',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-03-17 23:54:28'),
                'updated_at' => Carbon::parse('2023-03-17 23:55:32'),
                'remember_token' => 'NIqBT2JqJxffidjDwSy2iuNv50goMQFFEGCeP7GxQEw7WgKIPKDCDhlg22fO',
            ],
            [
                'id' => 84,
                'name' => 'Drs. Ec. M. Dadang Arjogunawan, M.Si',
                'email' => 'dadang.arjogunawan@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-03-18 18:33:40'),
                'password' => '$2y$10$qkXLf4QG1/oRxdeU370TcOOqJbanEnyxTkkI7lMpd/YTkApC86AiW',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-03-18 18:05:08'),
                'updated_at' => Carbon::parse('2023-03-18 18:33:40'),
                'remember_token' => null,
            ],
            [
                'id' => 85,
                'name' => 'Yoessy Etna Werdini, S.Psi., M.Si',
                'email' => 'yoessy.etna@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-03-20 20:38:09'),
                'password' => '$2y$10$O9FdfPHco6WYWVDnB8xUdOLHe7SgwUl.P.qBKEF5i071jMqavEv8G',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-03-20 20:37:23'),
                'updated_at' => Carbon::parse('2023-11-15 04:10:58'),
                'remember_token' => 'IbyH2GpMMCXZyYOvagc1tjRKcDdMQITCebNn7sdFeG6vRdFJNAoPzjrirNiy',
            ],
            [
                'id' => 87,
                'name' => 'Teguh Wijaya Mahdy, S.E.',
                'email' => 'teguh.mahdy@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-11 17:08:38'),
                'password' => '$2y$10$ZBM/RDunsOrE05e.OiKu2ukGHdJvt86sQQuyLektqrkNGJ1QJxl16',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-11 17:08:09'),
                'updated_at' => Carbon::parse('2023-04-11 17:08:38'),
                'remember_token' => 'bodHa0BpiwB35l3lsiO39hu8mu39N0pGzv2pqgiZ3VtNAUqI9vpqb5gSvj9Z',
            ],
            [
                'id' => 89,
                'name' => 'Emha Yuslifar, S.E.',
                'email' => 'emha.yuslifar@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-11 17:26:40'),
                'password' => '$2y$10$JAD00vCsDE7c9BIK645IxO0rrjwaMPyTxj7uTChaGm7EpA78wj9cS',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-11 17:26:06'),
                'updated_at' => Carbon::parse('2023-04-11 17:26:40'),
                'remember_token' => null,
            ],
            [
                'id' => 90,
                'name' => 'Agus Baharudin',
                'email' => 'agusbaha@ikbis.ac.id',
                'email_verified_at' => null,
                'password' => '$2y$10$RhUydsO/SPgOal86GVHL6e7kWoB.8yZQKte8c6kLYWENuHUTWwECa',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-12 17:44:39'),
                'updated_at' => Carbon::parse('2025-06-17 05:24:56'),
                'remember_token' => null,
            ],
            [
                'id' => 91,
                'name' => 'Yulia Megananda',
                'email' => 'mega.nanda@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-12 17:46:07'),
                'password' => '$2y$10$eVjyTY1xjl3zdHBltzmc/.S5W8dwGmaX2usvb7GNVIe0NUkSMUbzm',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-12 17:44:40'),
                'updated_at' => Carbon::parse('2023-04-12 17:46:07'),
                'remember_token' => 'kAJ7zk80T5UxMwqBK3KzKQRqy8AbuABZeVk8IJ8uBly3fXpYdb17zmZD98E5',
            ],
            [
                'id' => 92,
                'name' => 'Herdiyanto',
                'email' => 'herdiyanto@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-12 17:56:40'),
                'password' => '$2y$10$2Wffb5PLHnPtMz0QGH0DrupInwdFrylrA4UyQWMJpkaye01npwETi',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-12 17:45:42'),
                'updated_at' => Carbon::parse('2023-04-12 17:56:40'),
                'remember_token' => 'mnpnumjiAKQUHslz3RfIoJzDV8GXrkpIIUMbsa4EphIwQetAi1oCl0zPrWhH',
            ],
            [
                'id' => 93,
                'name' => 'Eka Pramudita. A.Md.Kom',
                'email' => 'eka.p@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-12 18:32:15'),
                'password' => '$2y$10$9DVBSFZgnPSMX8TR1iTlyeLHGXfuf/S3FXL24shSqoqQ77wCg6RaW',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-12 18:30:15'),
                'updated_at' => Carbon::parse('2023-05-25 18:35:36'),
                'remember_token' => 'S2iLtX9QQNQ7xJkl2vMSu7V05M93LwQLKdx5rvONT3j3jHEeeIEHEYE5ocq8',
            ],
            [
                'id' => 94,
                'name' => 'Muchamad Yudi, S.Pd.',
                'email' => 'muchamad.yudi@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-12 21:21:49'),
                'password' => '$2y$10$bnbPI3WV8fpIFmoq/O1hyulTCBYKhhKPfjBAfBstjeshgMdpfEYoG',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-12 18:45:07'),
                'updated_at' => Carbon::parse('2023-08-23 04:19:46'),
                'remember_token' => 'QrdCtjsoFtjQ7gI243SVhR9K48VFVSe44MAHnwMwi11lyIg91QgHQZN3Mzyq',
            ],
            [
                'id' => 95,
                'name' => 'Nur Solehatul Isnaini',
                'email' => 'nursolehatul@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-12 19:20:48'),
                'password' => '$2y$10$aQILSC2gLztdgtKRtUQZ4ucsfq5Qn9ztn/UBIaFT10h0NS2hltBjW',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-12 19:16:05'),
                'updated_at' => Carbon::parse('2023-04-12 19:20:48'),
                'remember_token' => null,
            ],
            [
                'id' => 96,
                'name' => 'Wahyu Bayu Candra Adinata, A.Md',
                'email' => 'wahyu.adinata@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-12 19:23:39'),
                'password' => '$2y$10$w6n0YoaM1URHyChs9Sbioec8fdQFzas84VF9tRiNMBXgn31p1RO4.',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-12 19:23:08'),
                'updated_at' => Carbon::parse('2023-04-12 19:23:39'),
                'remember_token' => '4mBjt6pEjHqeFrAGmp4pIalPKYdZ0w6RfMjUinf4jELE4R9GoZUwhE8A9C4G',
            ],
            [
                'id' => 97,
                'name' => 'Asmat, S.Kom',
                'email' => 'asmat@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-12 19:36:11'),
                'password' => '$2y$10$UcIi9EPQ/bZIeYx7WE0k2uOCrDOfzYzIcdaJozsQQY9DkYPNWqD/W',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-12 19:35:48'),
                'updated_at' => Carbon::parse('2023-04-12 19:36:11'),
                'remember_token' => 'DsS4CuOh3ZO8U39IN0Hd6xWbnKO3EfhTxiDMrLG2aJMtACyR5jkVimogJbem',
            ],
            [
                'id' => 101,
                'name' => 'Sri Mekar, SST,M.Mkes',
                'email' => 'sri.mekar@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-13 20:01:52'),
                'password' => '$2y$10$DSqA/yD3yKTGTazihzMAG.uvYtazyniw8Xbw1jGExqjtLrwqBiAti',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-13 20:01:20'),
                'updated_at' => Carbon::parse('2023-04-13 20:01:52'),
                'remember_token' => null,
            ],
            [
                'id' => 102,
                'name' => 'Sucahyono',
                'email' => 'sucahyono@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-13 20:22:19'),
                'password' => '$2y$10$SxaLog8trZoe.3aCFD4RBeNuDHOCOio0h5fRByzqyS4BdvTJ0DS/.',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-13 20:17:52'),
                'updated_at' => Carbon::parse('2023-04-13 20:22:19'),
                'remember_token' => null,
            ],
            [
                'id' => 103,
                'name' => 'fatimatuz zahra',
                'email' => 'fatimatuz.zahra@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-14 16:30:49'),
                'password' => '$2y$10$rspzL0kLe.jX7ZELmjEpSum4vE.Z36shxyQdeRHUmHwwZvqhv1IqG',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-14 16:01:15'),
                'updated_at' => Carbon::parse('2023-04-14 16:30:49'),
                'remember_token' => null,
            ],
            [
                'id' => 104,
                'name' => 'Budiono',
                'email' => 'budiono@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-14 18:02:52'),
                'password' => '$2y$10$XIXOPZFTZ7Mn6jvuXSxcR.euZ/Uqi1StpnziKmZeyoGzjpbBGh6oq',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-14 16:21:16'),
                'updated_at' => Carbon::parse('2023-04-14 18:02:52'),
                'remember_token' => null,
            ],
            [
                'id' => 105,
                'name' => 'Sujarwo',
                'email' => 'sujarwo@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-14 17:58:31'),
                'password' => '$2y$10$LalxvpM8adTyFMuBF0rV8O5u0FIxt3ngzqKR75b90jpjxDllXcQmq',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-14 16:22:31'),
                'updated_at' => Carbon::parse('2023-04-14 17:58:31'),
                'remember_token' => null,
            ],
            [
                'id' => 106,
                'name' => 'Abdul Khamid',
                'email' => 'abdul.khamid@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-14 18:11:58'),
                'password' => '$2y$10$.wnlhuHfljoa3DOLRKuuiuc4f4cQ.a4P4RiPSr2oaTKKiubvhwIuq',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-14 16:24:41'),
                'updated_at' => Carbon::parse('2023-04-14 18:11:58'),
                'remember_token' => 'r18NyUwHncfMH6Ucenas0gjDz4iLyUyX3FY9iM6l8eKY7wFNcx2E5JmkYKkk',
            ],
            [
                'id' => 107,
                'name' => 'Sukamdi',
                'email' => 'sukamdistikes@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-14 17:06:32'),
                'password' => '$2y$10$I0V9/elDALYX/WX7UlqgDu56h7wHcxu.cDGySIQoW6CjeV2f0FQIq',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-14 17:05:18'),
                'updated_at' => Carbon::parse('2023-04-14 17:06:32'),
                'remember_token' => null,
            ],
            [
                'id' => 108,
                'name' => 'Franky Luis Lesar, SE',
                'email' => 'franky.lesar@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-17 20:46:20'),
                'password' => '$2y$10$tVU42B41KylPrmdZ28w7Lec5Bn2LM.mcyfPP5Smb4rY5exp65BE3G',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-14 17:13:00'),
                'updated_at' => Carbon::parse('2023-04-17 20:46:20'),
                'remember_token' => 'QagpqPHDcMrLcNOPtiUQb7V5ZSDUqOwwmh6whdrqP3U3Vh1rwLULbM2FF6Z8',
            ],
            [
                'id' => 109,
                'name' => 'Agus Santoso',
                'email' => 'agus.santoso@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-14 18:27:23'),
                'password' => '$2y$10$zjIx7BAEo2QODA6ulUte1.XROMJx0qrDx.YD8YjUOWZPT0HtbrmSm',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-14 18:23:39'),
                'updated_at' => Carbon::parse('2023-04-14 18:27:23'),
                'remember_token' => null,
            ],
            [
                'id' => 110,
                'name' => 'Endang Sri Falupi',
                'email' => 'endang.falupi@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-14 20:08:31'),
                'password' => '$2y$10$x23Az6XmqIS5BXtXG.PYEOcwYdaN2Hyl8WeukQ7qjTKZI4o9M97cO',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-14 18:28:20'),
                'updated_at' => Carbon::parse('2023-04-14 20:08:31'),
                'remember_token' => null,
            ],
            [
                'id' => 111,
                'name' => 'Julien Jeanne Thyssen Paat',
                'email' => 'julien.paat@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-14 20:12:47'),
                'password' => '$2y$10$LFmY1LAe.7xj9njLiw.hG.f/pFfGAp7M8sPZ0C9mJV7wmqbF1RhPG',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-14 18:31:17'),
                'updated_at' => Carbon::parse('2023-04-14 20:12:47'),
                'remember_token' => null,
            ],
            [
                'id' => 112,
                'name' => 'Fauzan',
                'email' => 'fauzanstikes@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-14 20:25:50'),
                'password' => '$2y$10$4kEyMZ.2Tig5iylLRRRVOelu5X9piQ0eYzjl28jWM8S1OuJG2D1Fa',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-14 20:14:02'),
                'updated_at' => Carbon::parse('2023-04-14 20:25:50'),
                'remember_token' => null,
            ],
            [
                'id' => 113,
                'name' => 'Jarwo Ediyanto',
                'email' => 'jarwo.ediyanto@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-14 20:51:59'),
                'password' => '$2y$10$QVglfaYojIVA.RPvp2G7SeZuoiu4K62VJZeOpjUSze35lVn4ToRz.',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-14 20:27:04'),
                'updated_at' => Carbon::parse('2023-04-14 20:51:59'),
                'remember_token' => null,
            ],
            [
                'id' => 114,
                'name' => 'Radi',
                'email' => 'radi@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-14 21:05:45'),
                'password' => '$2y$10$m7yBMgX3Uo9ilBunZO8KsucJ4QC1K4xO6li9QIPPo/oJLtZERDYZy',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-14 20:53:21'),
                'updated_at' => Carbon::parse('2023-04-14 21:05:45'),
                'remember_token' => null,
            ],
            [
                'id' => 115,
                'name' => 'Rasmuji',
                'email' => 'rasmuji@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-14 21:11:25'),
                'password' => '$2y$10$JZqKYE79ubov71mwIdc60eAzmxAy65/qiFpLJ6LMyK3yu3Inv1OPy',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-14 21:07:09'),
                'updated_at' => Carbon::parse('2023-04-14 21:11:25'),
                'remember_token' => null,
            ],
            [
                'id' => 116,
                'name' => 'Rumiah',
                'email' => 'rumiah@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-14 21:16:47'),
                'password' => '$2y$10$9IGA/XNuMUh9LU4PDiQuiee3DXSPkoynBlHCDiFcS9fJRKg8/xscm',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-14 21:12:24'),
                'updated_at' => Carbon::parse('2023-04-14 21:16:47'),
                'remember_token' => null,
            ],
            [
                'id' => 119,
                'name' => 'Agus Prasetya, S.Pd,.M.Pd',
                'email' => 'agus.prasetya@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-18 02:37:43'),
                'password' => '$2y$10$JB.HXx/Nmt.40K7VgmgFjuew/QEeRf6FaK2pi6ru5GTZtB6yU.Y2K',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-18 02:28:40'),
                'updated_at' => Carbon::parse('2023-04-18 02:47:13'),
                'remember_token' => 'rd2EzbDMrUeg0zGspJ14xTXkxi32uyamCVdXx86BQ5751Fteo2ZoTQsPNAyx',
            ],
            [
                'id' => 120,
                'name' => 'Reva Mahardika',
                'email' => 'reva.mahardika@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-04-18 02:33:16'),
                'password' => '$2y$10$6/Pkev4TRNQ8bOHqmJwOuOKlzH8Xg.BR1HcrigX4lvC5FSSw0FGWi',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-04-18 02:28:58'),
                'updated_at' => Carbon::parse('2023-04-18 02:33:16'),
                'remember_token' => 'GiI9tjWN2nSymddp8HrqrCW0iMcslC3OALQZW5V7pu2rnNyQEl3yWiKRuxng',
            ],
            [
                'id' => 123,
                'name' => 'Dr .Ahmad Hariyanto, M.Si.,',
                'email' => 'ahmad.hariyanto@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-05-11 23:41:15'),
                'password' => '$2y$10$IchVEyjxTCZiBQL39TBeouMz0haS/Z6.GBbpYw0lXJRfg7ZFq.ZDa',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-05-11 23:36:55'),
                'updated_at' => Carbon::parse('2023-05-11 23:41:15'),
                'remember_token' => null,
            ],
            [
                'id' => 127,
                'name' => 'Rr Lies Setiyarini, A.Md.',
                'email' => 'lies.setyarini@ikbis.ac.id',
                'email_verified_at' => null,
                'password' => '$2y$10$wHiddfEhRaKuOVrpQXNsR.FcKQA0l41azhHqEJ6IC8KqVdao8UtbG',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-06-05 16:07:58'),
                'updated_at' => Carbon::parse('2025-07-11 12:54:02'),
                'remember_token' => null,
            ],
            [
                'id' => 128,
                'name' => 'Hosnollaili',
                'email' => 'hosnollail@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-06-20 14:28:59'),
                'password' => '$2y$10$f85dltOeXzBD9uaUC3WM/OQ8XbnGL/UifYtE.lZNBP/OoS2iPG5wW',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-06-20 14:19:24'),
                'updated_at' => Carbon::parse('2023-06-20 14:28:59'),
                'remember_token' => null,
            ],
            [
                'id' => 129,
                'name' => 'Mohammad Choirul Fajar',
                'email' => 'choirul.fajar@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-08-23 04:11:42'),
                'password' => '$2y$10$.X2WEAAnrk7dmz/Y/SnozO8VbOWIkYj/8VcqvibbN57xLo4mifoLu',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-08-23 04:10:04'),
                'updated_at' => Carbon::parse('2023-08-23 04:11:42'),
                'remember_token' => '5GjQrH88UYj281jGPP57pHBjWCdi0K6ZE2YqyQG7rfO0z7UxasgRQd0Rkpws',
            ],
            [
                'id' => 130,
                'name' => 'Setyo Wicaksono',
                'email' => 'setyo.wicaksono@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-08-24 03:54:01'),
                'password' => '$2y$10$V.HdaGIHZxfQLn9L9NAH2.Sby16v7naxjl03q9LtoqGN.R8x9vnoi',
                'is_active' => true,
                'created_at' => Carbon::parse('2023-08-24 03:43:55'),
                'updated_at' => Carbon::parse('2023-08-24 03:54:01'),
                'remember_token' => null,
            ],
            [
                'id' => 134,
                'name' => 'Agda Laily Ahadiya, S.Ak., M.M.',
                'email' => 'agda.ahadiya@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-08-24 03:54:01'),
                'password' => '$2a$12$iyABGBy3TxkcwvWmNgI/HuzwobjzgBlqCONK.mKxo9VgmB6NeUkrm',
                'is_active' => true,
                'created_at' => Carbon::parse('2024-07-08 00:35:40'),
                'updated_at' => Carbon::parse('2024-07-08 00:35:40'),
                'remember_token' => 'mzWem9tz5qiYRG6P40pii4XxpW5f3cmskuhEjpDj0Vpll12UknBYqU2LrIAd',
            ],
            [
                'id' => 135,
                'name' => 'Aditya Irawan',
                'email' => 'aditya.irawan@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-08-24 03:54:01'),
                'password' => '$2y$10$H4tnOEE.2hSi2QZmDOvYJuyY7aqVgehdFHezheXPhBmJa2azEm9xW',
                'is_active' => true,
                'created_at' => Carbon::parse('2024-11-21 20:11:47'),
                'updated_at' => Carbon::parse('2024-11-21 20:11:47'),
                'remember_token' => null,
            ],
            [
                'id' => 136,
                'name' => 'Suyahman',
                'email' => 'ahmad.ulumuddin@ikbis.ac.id',
                'email_verified_at' => null,
                'password' => '$2y$10$hxQz5DadOEedpx1MezaJze6J9HlD.jDWCSwutbPbfj1mVRY/5y7Zu',
                'is_active' => true,
                'created_at' => Carbon::parse('2024-12-15 23:14:07'),
                'updated_at' => Carbon::parse('2024-12-15 23:14:07'),
                'remember_token' => null,
            ],
            [
                'id' => 141,
                'name' => 'Argy Hariran Hindami',
                'email' => 'argy.hindami@ikbis.ac.id',
                'email_verified_at' => null,
                'password' => '$2y$10$9Hmba6g9L35E8sIHXqmg0.vcwrGUh568cO29G79h7odgnOwC.YtZC',
                'is_active' => true,
                'created_at' => Carbon::parse('2025-05-01 20:32:13'),
                'updated_at' => Carbon::parse('2025-05-01 20:32:13'),
                'remember_token' => null,
            ],
            [
                'id' => 142,
                'name' => 'Moh. Yuusuvianto',
                'email' => 'yusuvianto@ikbis.ac.id',
                'email_verified_at' => null,
                'password' => '$2y$10$9Hmba6g9L35E8sIHXqmg0.vcwrGUh568cO29G79h7odgnOwC.YtZC',
                'is_active' => true,
                'created_at' => Carbon::parse('2025-05-01 20:32:13'),
                'updated_at' => Carbon::parse('2025-05-01 20:32:13'),
                'remember_token' => null,
            ],
            [
                'id' => 143,
                'name' => 'Ir. Bambang Gunawan, M.Kes.',
                'email' => 'bambang.gunawan@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-02-21 21:00:19'),
                'password' => '$2a$12$pQcvEXcyHagmpI.PGzsx2.oQgmOJ/DR77QmvLRCVMtfEXwcWdIypS',
                'is_active' => true,
                'created_at' => Carbon::parse('2025-09-30 03:40:20'),
                'updated_at' => Carbon::parse('2025-09-30 03:40:20'),
                'remember_token' => null,
            ],
            [
                'id' => 149,
                'name' => 'Siti Khoirotun Nisak, S.Gz., M.Kes.',
                'email' => 'siti.khoirotun@ikbis.ac.id',
                'email_verified_at' => Carbon::parse('2023-02-21 21:00:19'),
                'password' => '$2a$12$pQcvEXcyHagmpI.PGzsx2.oQgmOJ/DR77QmvLRCVMtfEXwcWdIypS',
                'is_active' => true,
                'created_at' => Carbon::parse('2025-10-31 03:57:04'),
                'updated_at' => Carbon::parse('2025-10-31 03:57:04'),
                'remember_token' => 'h2riKAap0tU6O1lh4p5d6J5xrGWzlatHdegkASOnJhOHqkd0MkvSBdp19Jr9',
            ],
            [
                'id' => 150,
                'name' => 'Mochamad Syafruddin Aji',
                'email' => 'syafruddin.aji@ikbis.ac.id',
                'email_verified_at' => null,
                'password' => '$2y$10$KlfQXKzTjF9HYmYiB/91neLq/E6QmZsDtDByXb4OClCIEOHzlYNJm',
                'is_active' => true,
                'created_at' => Carbon::parse('2025-11-20 07:04:49'),
                'updated_at' => Carbon::parse('2025-11-20 07:04:49'),
                'remember_token' => null,
            ],
        ];

        foreach ($users as $user) {
            DB::table('users')->insert($user);
        }

        $this->command->info('Seeder users berhasil dijalankan!');
        $this->command->info('Total data: ' . count($users));
    }
}
